const data = {
  cells: [
    {
      type: 1,
      clues: [0, 40],
      answer: 'A',
      label: '1',
      index: 0,
      guess: 'X',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [0, 41],
      answer: 'B',
      label: '2',
      index: 1,
      guess: 'X',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [0, 42],
      answer: 'B',
      label: '3',
      index: 2,
      guess: 'X',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [0, 43],
      answer: 'A',
      label: '4',
      index: 3,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 4,
    },
    {
      type: 1,
      clues: [1, 44],
      answer: 'T',
      label: '5',
      index: 5,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [1, 45],
      answer: 'H',
      label: '6',
      index: 6,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [1, 46],
      answer: 'U',
      label: '7',
      index: 7,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [1, 47],
      answer: 'G',
      label: '8',
      index: 8,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [1, 48],
      answer: 'S',
      label: '9',
      index: 9,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 10,
    },
    {
      type: 1,
      clues: [2, 49],
      answer: 'A',
      label: '10',
      index: 11,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [2, 50],
      answer: 'J',
      label: '11',
      index: 12,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [2, 51],
      answer: 'A',
      label: '12',
      index: 13,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [2, 52],
      answer: 'R',
      label: '13',
      index: 14,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [3, 40],
      answer: 'S',
      label: '14',
      index: 15,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [3, 41],
      answer: 'L',
      index: 16,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [3, 42],
      answer: 'A',
      index: 17,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [3, 43],
      answer: 'B',
      index: 18,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 19,
    },
    {
      type: 1,
      clues: [4, 44],
      answer: 'R',
      label: '15',
      index: 20,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [4, 45],
      answer: 'E',
      index: 21,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [4, 46],
      answer: 'T',
      index: 22,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [4, 47],
      answer: 'R',
      index: 23,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [4, 48],
      answer: 'O',
      index: 24,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 25,
    },
    {
      type: 1,
      clues: [5, 49],
      answer: 'D',
      label: '16',
      index: 26,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [5, 50],
      answer: 'O',
      index: 27,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [5, 51],
      answer: 'L',
      index: 28,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [5, 52],
      answer: 'E',
      index: 29,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [6, 40],
      answer: 'A',
      label: '17',
      index: 30,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [6, 41],
      answer: 'U',
      index: 31,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [6, 42],
      answer: 'R',
      index: 32,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [6, 43],
      answer: 'A',
      index: 33,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 34,
    },
    {
      type: 1,
      clues: [7, 44],
      answer: 'A',
      label: '18',
      index: 35,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [7, 45],
      answer: 'R',
      index: 36,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [7, 46],
      answer: 'I',
      index: 37,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [7, 47],
      answer: 'A',
      index: 38,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [7, 48],
      answer: 'L',
      index: 39,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 40,
    },
    {
      type: 1,
      clues: [8, 49],
      answer: 'W',
      label: '19',
      index: 41,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [8, 50],
      answer: 'H',
      index: 42,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [8, 51],
      answer: 'E',
      index: 43,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [8, 52],
      answer: 'N',
      index: 44,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [9, 40],
      answer: 'P',
      label: '20',
      index: 45,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [9, 41],
      answer: 'E',
      index: 46,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [9, 42],
      answer: 'R',
      index: 47,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [9, 43],
      answer: 'S',
      index: 48,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [9, 53],
      answer: 'O',
      label: '21',
      index: 49,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [9, 44],
      answer: 'N',
      index: 50,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [9, 45],
      answer: 'A',
      index: 51,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [9, 46],
      answer: 'L',
      index: 52,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [9, 47],
      answer: 'F',
      index: 53,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [9, 48],
      answer: 'I',
      index: 54,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [9, 54],
      answer: 'N',
      label: '22',
      index: 55,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [9, 49],
      answer: 'A',
      index: 56,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [9, 50],
      answer: 'N',
      index: 57,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [9, 51],
      answer: 'C',
      index: 58,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [9, 52],
      answer: 'E',
      index: 59,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 60,
    },
    {
      type: 0,
      clues: [],
      index: 61,
    },
    {
      type: 1,
      clues: [10, 42],
      answer: 'Y',
      label: '23',
      index: 62,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [10, 43],
      answer: 'E',
      index: 63,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [10, 53],
      answer: 'A',
      index: 64,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [10, 44],
      answer: 'S',
      index: 65,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 66,
    },
    {
      type: 0,
      clues: [],
      index: 67,
    },
    {
      type: 0,
      clues: [],
      index: 68,
    },
    {
      type: 1,
      clues: [11, 48],
      answer: 'D',
      label: '24',
      index: 69,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [11, 54],
      answer: 'A',
      index: 70,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [11, 49],
      answer: 'R',
      index: 71,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [11, 50],
      answer: 'N',
      index: 72,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 73,
    },
    {
      type: 0,
      clues: [],
      index: 74,
    },
    {
      type: 1,
      clues: [12, 55],
      answer: 'T',
      label: '25',
      index: 75,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [12, 56],
      answer: 'A',
      label: '26',
      index: 76,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [12, 42],
      answer: 'B',
      index: 77,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 78,
    },
    {
      type: 1,
      clues: [13, 53],
      answer: 'F',
      label: '27',
      index: 79,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [13, 44],
      answer: 'I',
      index: 80,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [13, 57],
      answer: 'N',
      label: '28',
      index: 81,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [13, 58],
      answer: 'A',
      label: '29',
      index: 82,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [13, 59],
      answer: 'L',
      label: '30',
      index: 83,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [13, 48],
      answer: 'L',
      index: 84,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [13, 54],
      answer: 'Y',
      index: 85,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 86,
    },
    {
      type: 1,
      clues: [14, 50],
      answer: 'Y',
      label: '31',
      index: 87,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [14, 60],
      answer: 'D',
      label: '32',
      index: 88,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [14, 61],
      answer: 'S',
      label: '33',
      index: 89,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [15, 55],
      answer: 'A',
      label: '34',
      index: 90,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [15, 56],
      answer: 'T',
      index: 91,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [15, 42],
      answer: 'O',
      index: 92,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [15, 62],
      answer: 'M',
      label: '35',
      index: 93,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 94,
    },
    {
      type: 1,
      clues: [16, 44],
      answer: 'T',
      label: '36',
      index: 95,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [16, 57],
      answer: 'O',
      index: 96,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [16, 58],
      answer: 'D',
      index: 97,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [16, 59],
      answer: 'A',
      index: 98,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [16, 48],
      answer: 'Y',
      index: 99,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 100,
    },
    {
      type: 1,
      clues: [17, 63],
      answer: 'I',
      label: '37',
      index: 101,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [17, 50],
      answer: 'C',
      index: 102,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [17, 60],
      answer: 'E',
      index: 103,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [17, 61],
      answer: 'T',
      index: 104,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [18, 55],
      answer: 'C',
      label: '38',
      index: 105,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [18, 56],
      answer: 'O',
      index: 106,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [18, 42],
      answer: 'N',
      index: 107,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [18, 62],
      answer: 'A',
      index: 108,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [18, 64],
      answer: 'N',
      label: '39',
      index: 109,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 110,
    },
    {
      type: 1,
      clues: [19, 57],
      answer: 'T',
      label: '40',
      index: 111,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [19, 58],
      answer: 'A',
      index: 112,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [19, 59],
      answer: 'S',
      index: 113,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 114,
    },
    {
      type: 1,
      clues: [20, 65],
      answer: 'I',
      label: '41',
      index: 115,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [20, 63],
      answer: 'N',
      index: 116,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [20, 50],
      answer: 'A',
      index: 117,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [20, 60],
      answer: 'N',
      index: 118,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [20, 61],
      answer: 'E',
      index: 119,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [21, 55],
      answer: 'I',
      label: '42',
      index: 120,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [21, 56],
      answer: 'N',
      index: 121,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [21, 42],
      answer: 'D',
      index: 122,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [21, 62],
      answer: 'I',
      index: 123,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [21, 64],
      answer: 'A',
      index: 124,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 125,
    },
    {
      type: 1,
      clues: [22, 57],
      answer: 'A',
      label: '43',
      index: 126,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [22, 58],
      answer: 'M',
      index: 127,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [22, 59],
      answer: 'T',
      index: 128,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 129,
    },
    {
      type: 1,
      clues: [23, 65],
      answer: 'M',
      label: '44',
      index: 130,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [23, 63],
      answer: 'A',
      index: 131,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [23, 50],
      answer: 'S',
      index: 132,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [23, 60],
      answer: 'S',
      index: 133,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [23, 61],
      answer: 'E',
      index: 134,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [24, 55],
      answer: 'T',
      label: '45',
      index: 135,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [24, 56],
      answer: 'E',
      index: 136,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [24, 42],
      answer: 'S',
      index: 137,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [24, 62],
      answer: 'L',
      index: 138,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [24, 64],
      answer: 'A',
      index: 139,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 140,
    },
    {
      type: 1,
      clues: [25, 57],
      answer: 'C',
      label: '46',
      index: 141,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [25, 58],
      answer: 'S',
      index: 142,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [25, 59],
      answer: 'I',
      index: 143,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 144,
    },
    {
      type: 1,
      clues: [26, 65],
      answer: 'A',
      label: '47',
      index: 145,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [26, 63],
      answer: 'S',
      index: 146,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [26, 50],
      answer: 'H',
      index: 147,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [26, 60],
      answer: 'E',
      index: 148,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [26, 61],
      answer: 'D',
      index: 149,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 150,
    },
    {
      type: 0,
      clues: [],
      index: 151,
    },
    {
      type: 0,
      clues: [],
      index: 152,
    },
    {
      type: 1,
      clues: [27, 62],
      answer: 'O',
      label: '48',
      index: 153,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [27, 64],
      answer: 'N',
      index: 154,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [27, 66],
      answer: 'T',
      label: '49',
      index: 155,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [27, 57],
      answer: 'H',
      index: 156,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [27, 58],
      answer: 'I',
      index: 157,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [27, 59],
      answer: 'N',
      index: 158,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [27, 67],
      answer: 'I',
      label: '50',
      index: 159,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [27, 65],
      answer: 'C',
      index: 160,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [27, 63],
      answer: 'E',
      index: 161,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 162,
    },
    {
      type: 0,
      clues: [],
      index: 163,
    },
    {
      type: 0,
      clues: [],
      index: 164,
    },
    {
      type: 1,
      clues: [28, 68],
      answer: 'C',
      label: '51',
      index: 165,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [28, 69],
      answer: 'Z',
      label: '52',
      index: 166,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [28, 70],
      answer: 'A',
      label: '53',
      index: 167,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [28, 62],
      answer: 'R',
      index: 168,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 169,
    },
    {
      type: 1,
      clues: [29, 66],
      answer: 'W',
      label: '54',
      index: 170,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [29, 57],
      answer: 'A',
      index: 171,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [29, 58],
      answer: 'L',
      index: 172,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [29, 59],
      answer: 'L',
      index: 173,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [29, 67],
      answer: 'S',
      index: 174,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 175,
    },
    {
      type: 1,
      clues: [30, 63],
      answer: 'C',
      label: '55',
      index: 176,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [30, 71],
      answer: 'O',
      label: '56',
      index: 177,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [30, 72],
      answer: 'W',
      label: '57',
      index: 178,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [30, 73],
      answer: 'S',
      label: '58',
      index: 179,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [31, 68],
      answer: 'H',
      label: '59',
      index: 180,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [31, 69],
      answer: 'E',
      index: 181,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [31, 70],
      answer: 'L',
      index: 182,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [31, 62],
      answer: 'D',
      index: 183,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 184,
    },
    {
      type: 1,
      clues: [32, 66],
      answer: 'A',
      label: '60',
      index: 185,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [32, 57],
      answer: 'N',
      index: 186,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [32, 58],
      answer: 'V',
      index: 187,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [32, 59],
      answer: 'I',
      index: 188,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [32, 67],
      answer: 'L',
      index: 189,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 190,
    },
    {
      type: 1,
      clues: [33, 63],
      answer: 'O',
      label: '61',
      index: 191,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [33, 71],
      answer: 'V',
      index: 192,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [33, 72],
      answer: 'E',
      index: 193,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [33, 73],
      answer: 'N',
      index: 194,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [34, 68],
      answer: 'A',
      label: '62',
      index: 195,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [34, 69],
      answer: 'R',
      index: 196,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [34, 70],
      answer: 'S',
      index: 197,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [34, 62],
      answer: 'E',
      index: 198,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 199,
    },
    {
      type: 1,
      clues: [35, 66],
      answer: 'S',
      label: '63',
      index: 200,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [35, 57],
      answer: 'C',
      index: 201,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [35, 58],
      answer: 'E',
      index: 202,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [35, 59],
      answer: 'N',
      index: 203,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [35, 67],
      answer: 'E',
      index: 204,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 205,
    },
    {
      type: 1,
      clues: [36, 63],
      answer: 'N',
      label: '64',
      index: 206,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [36, 71],
      answer: 'E',
      index: 207,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [36, 72],
      answer: 'R',
      index: 208,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [36, 73],
      answer: 'O',
      index: 209,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [37, 68],
      answer: 'P',
      label: '65',
      index: 210,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [37, 69],
      answer: 'O',
      index: 211,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [37, 70],
      answer: 'O',
      index: 212,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [37, 62],
      answer: 'R',
      index: 213,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 214,
    },
    {
      type: 0,
      clues: [],
      index: 215,
    },
    {
      type: 1,
      clues: [38, 57],
      answer: 'E',
      label: '66',
      index: 216,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [38, 58],
      answer: 'R',
      index: 217,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [38, 59],
      answer: 'E',
      index: 218,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 0,
      clues: [],
      index: 219,
    },
    {
      type: 0,
      clues: [],
      index: 220,
    },
    {
      type: 1,
      clues: [39, 63],
      answer: 'D',
      label: '67',
      index: 221,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [39, 71],
      answer: 'R',
      index: 222,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [39, 72],
      answer: 'E',
      index: 223,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
    {
      type: 1,
      clues: [39, 73],
      answer: 'W',
      index: 224,
      guess: '',
      penciled: false,
      checked: false,
      confirmed: false,
      revealed: false,
      modified: false,
      timestamp: 1637641940,
    },
  ],
  status: {
    firsts: {
      cleared: 1637641162,
      opened: 1637641125,
      timerReset: 1637641940,
    },
    isSolved: false,
    isFilled: false,
    autocheckEnabled: false,
    blankCells: 186,
    incorrectCells: 186,
    lastCommitID: 'md6t6e',
    currentProgress: null,
  },
  timer: {
    totalElapsedTime: 16,
    sessionElapsedTime: 0,
    resetSinceLastCommit: false,
    sessionStartTimestamp: 1637979814,
  },
  selection: {
    cell: 0,
    cellClues: [0, 40],
    clue: 0,
    clueCells: [0, 1, 2, 3],
    clueList: 0,
    relatedCells: [],
    relatedClues: [],
  },
};

setTimeout(() => {
  //   render(data.cells);
  readGrid();
}, 3000);

function writeGrid(cells) {
  for (let i = 0; i < 200; i++) setCellValue(i, 'X');
}

function setCellValue(cellIndex, value) {
  if (cellIndex.type === 0) {
    return;
  }
  const id = `cell-id-${cellIndex}`;
  console.log(id);
  const cellGroup = document.getElementById(id).parentElement;
  const cellText =
    cellGroup.querySelectorAll('text')[2] ||
    cellGroup.querySelectorAll('text')[0];
  try {
    cellText.childNodes[1].textContent = '9';
  } catch (err) {}
}

function readGrid() {
  const board = document.querySelector('[data-group=cells]');
  const cells = [];
  board.childNodes.forEach((cellGroup, i) => {
    if (
      cellGroup.querySelector('rect').className.baseVal.includes('Cell-block')
    )
      return cells.push({
        value: '',
        index: i,
        type: 0,
      });
    const cellText =
      cellGroup.querySelectorAll('text')[2] ||
      cellGroup.querySelectorAll('text')[0];
    if (cellText) {
      return cells.push({
        value: cellText.childNodes[1].textContent,
        index: i,
        type: 1,
      });
    }
  });
  console.log(cells);
}
